-- MySQL Script generated by MySQL Workbench
-- Thu Nov 21 19:54:22 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`animator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`animator` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`speciality`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`speciality` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `speicality_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`agency`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`agency` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `speciality_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_agency_speicality1_idx` (`speciality_id` ASC) VISIBLE,
  CONSTRAINT `fk_agency_speicality1`
    FOREIGN KEY (`speciality_id`)
    REFERENCES `mydb`.`speciality` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`location` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `house` VARCHAR(45) NOT NULL,
  `street` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`event` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `animator_id` INT NOT NULL,
  `agency_id` INT NOT NULL,
  `location_id` INT NOT NULL,
  `type_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_event_animator1_idx` (`animator_id` ASC) VISIBLE,
  INDEX `fk_event_agency1_idx` (`agency_id` ASC) VISIBLE,
  INDEX `fk_event_location1_idx` (`location_id` ASC) VISIBLE,
  INDEX `fk_event_type1_idx` (`type_id` ASC) VISIBLE,
  CONSTRAINT `fk_event_animator1`
    FOREIGN KEY (`animator_id`)
    REFERENCES `mydb`.`animator` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_agency1`
    FOREIGN KEY (`agency_id`)
    REFERENCES `mydb`.`agency` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_location1`
    FOREIGN KEY (`location_id`)
    REFERENCES `mydb`.`location` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_type1`
    FOREIGN KEY (`type_id`)
    REFERENCES `mydb`.`type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`wedding`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`wedding` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `event_date` DATE NOT NULL,
  `duration` TIME NOT NULL,
  `value` DECIMAL NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`event_wedding`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`event_wedding` (
  `event_id` INT NOT NULL,
  `wedding_id` INT NOT NULL,
  PRIMARY KEY (`event_id`, `wedding_id`),
  INDEX `fk_event_wedding_wedding1_idx` (`wedding_id` ASC) VISIBLE,
  CONSTRAINT `fk_event_wedding_event1`
    FOREIGN KEY (`event_id`)
    REFERENCES `mydb`.`event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_wedding_wedding1`
    FOREIGN KEY (`wedding_id`)
    REFERENCES `mydb`.`wedding` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`birthday`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`birthday` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `event_date` DATE NOT NULL,
  `duration` TIME NOT NULL,
  `value` DECIMAL NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`kidparty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`kidparty` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `event_date` DATE NOT NULL,
  `duration` TIME NOT NULL,
  `value` DECIMAL NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`firstsep`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`firstsep` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `event_date` DATE NOT NULL,
  `duration` TIME NOT NULL,
  `value` DECIMAL NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`christmass`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`christmass` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `event_date` DATE NOT NULL,
  `duration` TIME NOT NULL,
  `value` DECIMAL NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`newyear`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`newyear` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `event_date` DATE NOT NULL,
  `duration` TIME NOT NULL,
  `value` DECIMAL NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`event_birthday`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`event_birthday` (
  `event_id` INT NOT NULL,
  `birthday_id` INT NOT NULL,
  PRIMARY KEY (`event_id`, `birthday_id`),
  INDEX `fk_event_birthday_birthday1_idx` (`birthday_id` ASC) VISIBLE,
  CONSTRAINT `fk_event_birthday_birthday1`
    FOREIGN KEY (`birthday_id`)
    REFERENCES `mydb`.`birthday` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_birthday_event1`
    FOREIGN KEY (`event_id`)
    REFERENCES `mydb`.`event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`event_kidparty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`event_kidparty` (
  `event_id` INT NOT NULL,
  `kidparty_id` INT NOT NULL,
  PRIMARY KEY (`event_id`, `kidparty_id`),
  INDEX `fk_event_kidparty_kidparty1_idx` (`kidparty_id` ASC) VISIBLE,
  CONSTRAINT `fk_event_kidparty_kidparty1`
    FOREIGN KEY (`kidparty_id`)
    REFERENCES `mydb`.`kidparty` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_kidparty_event1`
    FOREIGN KEY (`event_id`)
    REFERENCES `mydb`.`event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`event_firstsep`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`event_firstsep` (
  `event_id` INT NOT NULL,
  `firstsep_id` INT NOT NULL,
  PRIMARY KEY (`event_id`, `firstsep_id`),
  INDEX `fk_event_firstsep_firstsep1_idx` (`firstsep_id` ASC) VISIBLE,
  CONSTRAINT `fk_event_firstsep_firstsep1`
    FOREIGN KEY (`firstsep_id`)
    REFERENCES `mydb`.`firstsep` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_firstsep_event1`
    FOREIGN KEY (`event_id`)
    REFERENCES `mydb`.`event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`event_christmass`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`event_christmass` (
  `event_id` INT NOT NULL,
  `christmass_id` INT NOT NULL,
  PRIMARY KEY (`event_id`, `christmass_id`),
  INDEX `fk_event_christmass_christmass1_idx` (`christmass_id` ASC) VISIBLE,
  CONSTRAINT `fk_event_christmass_christmass1`
    FOREIGN KEY (`christmass_id`)
    REFERENCES `mydb`.`christmass` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_christmass_event1`
    FOREIGN KEY (`event_id`)
    REFERENCES `mydb`.`event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`event_newyear`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`event_newyear` (
  `event_id` INT NOT NULL,
  `newyear_id` INT NOT NULL,
  PRIMARY KEY (`event_id`, `newyear_id`),
  INDEX `fk_event_newyear_newyear1_idx` (`newyear_id` ASC) VISIBLE,
  CONSTRAINT `fk_event_newyear_newyear1`
    FOREIGN KEY (`newyear_id`)
    REFERENCES `mydb`.`newyear` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_newyear_event1`
    FOREIGN KEY (`event_id`)
    REFERENCES `mydb`.`event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
