COMMON: &common
  DEBUG: False
  SQLALCHEMY_TRACK_MODIFICATIONS: False

development:
  <<: *common
  DEBUG: True
#  SQLALCHEMY_DATABASE_URI: 'sqlite://'
#  SQLALCHEMY_DATABASE_URI: 'sqlite:///device_db.sqlite'
  SQLALCHEMY_DATABASE_URI: 'mysql+pymysql://lab1db:Helloworld25@lab1-121-db.mysql.database.azure.com:3306/lab4?ssl_disabled=true'

production:
  <<: *common
  SQLALCHEMY_DATABASE_URI: 'mysql+pymysql://lab1db:Helloworld25@lab1-121-db.mysql.database.azure.com:3306/lab4?ssl_disabled=true'

ADDITIONAL_CONFIG:
  MYSQL_ROOT_USER: lab1db
  MYSQL_ROOT_PASSWORD: Helloworld25

