name: lab1
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          port: 22
          script: |
            cd /home/${{ secrets.AZURE_USER }}/lab1ad/db_lb/data_base_lab-lab4/lab4/app
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
