from my_project.auth.domain.orders.animator import Animator
from my_project.auth.domain.orders.speciality import Speciality
from my_project.auth.domain.orders.agency import Agency
from my_project.auth.domain.orders.location import Location
from my_project.auth.domain.orders.event_type import EventType
from my_project.auth.domain.orders.event import Event
from my_project.auth.domain.orders.wedding import Wedding
from my_project.auth.domain.orders.event_wedding import EventWedding
from my_project.auth.domain.orders.birthday import Birthday
from my_project.auth.domain.orders.event_birthday import EventBirthday
from my_project.auth.domain.orders.kidparty import KidParty
from my_project.auth.domain.orders.event_kidparty import EventKidParty
from my_project.auth.domain.orders.firstsep import FirstSep
from my_project.auth.domain.orders.event_firstsep import EventFirstSep
from my_project.auth.domain.orders.christmass import Christmass
from my_project.auth.domain.orders.event_christmass import EventChristmass
from my_project.auth.domain.orders.newyear import NewYear
from my_project.auth.domain.orders.event_newyear import EventNewYear
